server:
  port: 8300
spring:
  application:
    name: consumer-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
